services:
  # Combined Backend + Frontend Service
  - type: web
    name: cook-next-door-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:combined
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
